name: Resolve Timeouts
description: Resolves test/build timeouts from input, repo var, project config, or action fallback.

inputs:
  timeoutTestsInput:
    description: Direct input override for test timeout (minutes)
    required: false
  timeoutTestsRepoVar:
    description: Repository variable fallback for test timeout
    required: false
  timeoutBuildInput:
    description: Direct input override for build timeout (minutes)
    required: false
  timeoutBuildRepoVar:
    description: Repository variable fallback for build timeout
    required: false
  projectDefaultsFile:
    description: Optional path to project-level defaults.json
    required: false
    default: .github/config/defaults.json

outputs:
  timeoutMinutesTests:
    description: Final resolved test timeout
    value: ${{ steps.resolve.outputs.timeoutMinutesTests }}
  timeoutMinutesBuild:
    description: Final resolved build timeout
    value: ${{ steps.resolve.outputs.timeoutMinutesBuild }}

runs:
  using: composite
  steps:
    - name: Make script executable
      shell: bash
      run: chmod +x "${{ github.action_path }}/resolve-timeouts.sh"

    - id: resolve
      name: Determine timeouts
      shell: bash
      env:
        TIMEOUT_TESTS_INPUT:    ${{ inputs.timeoutTestsInput }}
        TIMEOUT_TESTS_REPO_VAR: ${{ inputs.timeoutTestsRepoVar }}
        TIMEOUT_BUILD_INPUT:    ${{ inputs.timeoutBuildInput }}
        TIMEOUT_BUILD_REPO_VAR: ${{ inputs.timeoutBuildRepoVar }}
        PROJECT_DEFAULTS_FILE:  ${{ inputs.projectDefaultsFile }}
        ACTION_DEFAULTS_FILE:   ${{ github.action_path }}/defaults.json
      run: bash "${{ github.action_path }}/resolve-timeouts.sh"
