name: Resolve Project Name
description: Resolves and sanitizes project name with layered priority logic.

inputs:
  projectNameInput:
    description: Input override for project name
    required: false
  projectNameRepoVar:
    description: Repository variable fallback for project name
    required: false
  defaultsFileOverride:
    description: Optional custom defaults.json path (workspace-relative)
    required: false

outputs:
  sanitized_name:
    description: The sanitized project name
    value: ${{ steps.resolve.outputs.sanitized_name }}

runs:
  using: composite
  steps:
    - name: Make script executable
      shell: bash
      run: chmod +x "${{ github.action_path }}/resolve-project-name.sh"

    - id: resolve
      shell: bash
      env:
        INPUT_NAME: ${{ inputs.projectNameInput }}
        REPO_VAR_NAME: ${{ inputs.projectNameRepoVar }}
        DEFAULTS_FILE_OVERRIDE: ${{ inputs.defaultsFileOverride }}
        ACTION_DEFAULTS_FILE: ${{ github.action_path }}/defaults.json
      run: |
        bash "${{ github.action_path }}/resolve-project-name.sh"
