name: 🌀 Dry Deploy

on:
  workflow_call:
    inputs:
      runnerMain:
        type: string
        required: false
      deployTargets:
        description: "JSON array of deploy targets (e.g. [\"itch.io\", \"s3\"])"
        required: true
        type: string
      successfulTargets:
        description: "JSON array of targets to simulate as successful (rest will fail)"
        required: false
        default: '[]'
        type: string

    outputs:
      deployResult:
        description: "Overall simulated deploy result (success if all succeed, fail otherwise)"
        value: ${{ jobs.dry_deploy.outputs.deployResult }}

jobs:
  dry_deploy:
    name: 🛠 Simulate Deployments
    runs-on: ${{ inputs.runnerMain }}
    defaults:
      run:
        shell: bash
    outputs:
      deployResult: ${{ steps.simulate.outputs.deployResult }}
    steps:
      - name: Simulate Deployments
        id: simulate
        run: |
          ALL_TARGETS=$(echo '${{ inputs.deployTargets }}' | jq -r '.[]')
          SUCCESS_TARGETS=$(echo '${{ inputs.successfulTargets }}' | jq -r '.[]')

          mkdir -p simulated-deploy-results

          OVERALL_SUCCESS=true

          for TARGET in $ALL_TARGETS; do
            if echo "$SUCCESS_TARGETS" | grep -q "^$TARGET$"; then
              STATUS="success"
              NOTE="Simulated successful deployment"
            else
              STATUS="failure"
              NOTE="Simulated failure"
              OVERALL_SUCCESS=false
            fi

            printf '{\n  "target": "%s",\n  "status": "%s",\n  "note": "%s"\n}\n' \
            "$TARGET" "$STATUS" "$NOTE" > simulated-deploy-results/${TARGET}.json
          done

          echo "Overall deploy result: $OVERALL_SUCCESS"
          echo "deployResult=$([[ $OVERALL_SUCCESS == true ]] && echo success || echo failure)" >> $GITHUB_OUTPUT

      - name: Upload Simulated Deploy Result Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: simulated-deployment-results
          path: simulated-deploy-results