name: 🧪 Test - Step 2 Build Workflow

on:
  workflow_dispatch:
    inputs:
      unityVersion:
        description: "Specific unity version to test on"
        required: false
        default: "auto"
        type: string
      buildType:
        description: "preview = build only!"
        required: true
        default: "preview"
        type: choice
        options:
          - preview
          - release_candidate
          - release
      buildVersion:
        description: "Optional version string (e.g. v1.2.3 or v1.2.3-rc.1). Leave blank to auto-generate (e.g. PR-0001, manual-main)"
        required: false
        default: "v0.0.0"
        type: string
      projectName:
        description: "Project name for artifacts"
        required: true
        default: "Unity_CI_Templates"
      buildTargets:
        description: "JSON array of build targets to build"
        required: true
        default: '["WebGL", "StandaloneWindows64"]'
      deployTargets:
        description: "JSON array of deploy targets (e.g. [\"itch.io\",\"s3\"])"
        required: true
        default: '["steam", "gh-pages"]'
        type: string

permissions:
  contents: write

jobs:
  prepare_metadata:
    name: ⏳ Prepare Metadata
    uses: ./.github/workflows/prepare-metadata.yml
    with:
      runnerMain: "ubuntu-latest"
      runnerMacos: "macos-latest"
      projectName: ${{ inputs.projectName }}
      unityVersion: ${{ inputs.unityVersion }}
      skipTests: true
      testsOnly: false
      buildTargets: ${{ inputs.buildTargets }}
      deployTargets: ${{ inputs.deployTargets }}
      buildType: ${{ inputs.buildType }}
      buildVersion: ${{ inputs.buildVersion }}

  test_build:
    name: 🧩 Test Unity Build
    needs: prepare_metadata
    uses: ./.github/workflows/step-2-build.yml
    with:
      runnerMain: "ubuntu-latest"
      runnerMacos: "macos-latest"
      unityVersion: ${{ needs.prepare_metadata.outputs.unityVersion }}
      buildVersion: ${{ needs.prepare_metadata.outputs.buildVersion }}
      buildType: ${{ needs.prepare_metadata.outputs.buildType }}
      projectName: ${{ needs.prepare_metadata.outputs.projectName }}
      buildTargets: ${{ inputs.buildTargets }}
      combineArtifacts: ${{ needs.prepare_metadata.outputs.requiresCombined }}
    secrets:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}